name: RaidCraft-API
main: de.raidcraft.RaidCraftBasePlugin
version: ${project.version}#${build.number}
author: Silthus, IDragonfire
website: www.raid-craft.eu
softdepend: [WorldGuard, WorldEdit]
database: true