name: RaidCraft-API
main: de.raidcraft.RaidCraftPlugin
version: ${project.version}#${build.number}
author: Silthus
website: www.raid-craft.de
depend: [LibsDisguises, WorldEdit, WorldGuard, EffectLib]
softdepend: [Citizens]
database: true
api-version: 1.13